// src/brew-monitor.frontend/src/components/statistics/components/status/index.tsx
import React, { FC } from 'react';
import LinearProgress from '@material-ui/core/LinearProgress';
import Box from '@material-ui/core/Box';
import './styles.scss';
import Brew from '../../../../types/Brew';

type StatusProps = {
  activeBrew: Brew;
};

const Status: FC<StatusProps> = ({ activeBrew }) => {
  const calculateProgress = (): number => {
    const brewDate = new Date(activeBrew.createdAt);
    const diff = Math.floor((+Date.now() - +brewDate) / (1000 * 60 * 60 * 24));
    return (diff * 100) / activeBrew.fermentationTime;
  };
  return (
    <Box className="status">
      <h3>Fermentation progress</h3>
      <LinearProgress variant="determinate" value={activeBrew && calculateProgress()} style={{ borderRadius: '2px' }} />
    </Box>
  );
};

export default Status;

// src/brew-monitor.Frontend/src/app/brew-page/status/status.component.ts
import { Component, OnInit, Input } from "@angular/core";
import { IBrewModel } from "src/app/shared/services/brew/brew.service";
import { DetailsService } from "../../shared/services/details/details.service";

@Component({
  selector: "brew-page-status",
  templateUrl: "./status.component.html",
  styleUrls: ["./status.component.scss"],
})
export class StatusComponent implements OnInit {
  @Input() activeBrew: IBrewModel;
  status: number;

  constructor(private _detailsService: DetailsService) {}

  ngOnInit(): void {
    this.status = this.calculateFermentationProgress();
  }

  calculateFermentationProgress(): number {
    let brewDetails = this._detailsService.getBrewDetails(this.activeBrew.id);
    let diff = Math.floor(
      (+Date.now() - +brewDetails.brewDate) / (1000 * 60 * 60 * 24)
    );
    return (diff * 100) / brewDetails.fermentationDays;
  }
}

<div class="status">
  <div class="status__header">
    <h4>Fermentation progress</h4>
  </div>
  <div class="status__fermentation">
    <mat-progress-bar mode="determinate" value="status"></mat-progress-bar>
  </div>
</div>
